#!/usr/bin/env php
<?php

require_once __DIR__.'/../../vendor/autoload.php';

use Ayuco\Listener;
use WPMVC\Commands\SetNameCommand;
use WPMVC\Commands\SetupCommand;
use WPMVC\Commands\RegisterCommand;

$ayuco = new Listener();

$ayuco->register(new SetupCommand(__DIR__));
$ayuco->register(new RegisterCommand(__DIR__));

$ayuco->interpret();